# SITE CONFIGURATION
baseurl: 
url: "https://hanbikim.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Hanbi Kim ğŸ‘©ğŸ»â€ğŸ’»
  avatar: assets/img/avatar.png  # í”„ë¡œí•„ ì´ë¯¸ì§€
  favicon: assets/img/sun.jpeg
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text:
     <p></p>
  header_text_feature_image: assets/img/ny2.jpg
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: false
  email_address: "hanbikim20@g.cbnu.ac.kr"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "hanbikim/"
  gitter:
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/hanbi-kim/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: Nanum+Gothic:wght@400;700,Source+Sans+Pro:ital,wght@0,400;0,700;1,400;1,700

  # Post navigation
  post_navigation: true


google-site-verification: "wOfnu0L7yUEXXPYcN3bsI7PfA1Pl_YbT0VtbptZf5JM"
 
encoding: "utf-8"
# Configure the plugin here
# category_path: "category" # <- default value
category_layout: "category.html" # <- default value

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

animation: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
